version: '2'
services:
  app:
    image: node:14-alpine
    volumes:
      - .:/app:delegated
    ports:
      - 8080:8080
    working_dir: /app
    # prettier-ignore
    command: ["npm", "run", "watch"]
