version: '2'
services:
  app:
    image: node:14-alpine
    volumes:
      - .:/app:delegated
    ports:
      - 80:80
    working_dir: /app
    # prettier-ignore
    command: ["npm", "run", "start"]
  watch:
    image: node:14-alpine
    volumes:
      - .:/app:delegated
    working_dir: /app
    # prettier-ignore
    command: ["npm", "run", "watch"]
