on:
  push:
  pull_request:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make build

      # TODO: this prolly fails with PRs due to no secrets access
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: docker push famousgarkin/shepherd:latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - run: |
          docker tag famousgarkin/shepherd $IMAGE
          docker push $IMAGE
        env:
          IMAGE: famousgarkin/shepherd:${{ github.event.release.tag_name }}
        if: ${{ github.event_name == 'release' }}
