on:
  push:
  pull_request:
  release:
    types:
      - published
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: ./.github/scripts/docker-build

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: ./.github/scripts/docker-push famousgarkin/shepherd:latest
        if: ${{ github.ref == 'refs/heads/master' }}

      - run: ./.github/scripts/docker-push famousgarkin/shepherd:${{ github.event.release.tag_name }}
        if: ${{ github.event_name == 'release' }}
